<a href="https://colab.research.google.com/github/naiksahana/SQL-MurderMystery/blob/main/SQLMurderMystery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3 as sql

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
conn = sql.connect('/content/drive/My Drive/sql-murder-mystery.db')

In [ ]:
import pandas as pd

In [ ]:
conn

In [ ]:
query="""
SELECT *
FROM crime_scene_report
WHERE city="SQL City" AND date='20180115' AND type='murder'
ORDER BY date;
"""
#pd.read_sql_query(query,conn)

In [ ]:
pd.read_sql_query(query,conn)

,date,type,description,city
0,20180115,murder,Security footage shows that there were 2 witne...,SQL City

In [ ]:
query1="""
SELECT *
FROM person
where address_street_name="Northwestern Dr" Order by address_number
;
"""

In [ ]:
pd.read_sql_query(query1,conn)

,id,name,license_id,address_number,address_street_name,ssn
0,89906,Kinsey Erickson,510019,309,Northwestern Dr,635287661
1,15171,Weldon Penso,336999,311,Northwestern Dr,131379495
2,40336,Fredia Billeter,251082,404,Northwestern Dr,108056488
3,85280,Donn Duin,569122,540,Northwestern Dr,613873810
4,12711,Norman Apolito,667757,599,Northwestern Dr,778264744
5,75484,Del Tacderen,447887,607,Northwestern Dr,243821337
6,26758,Angelena Billman,942074,629,Northwestern Dr,341854756
7,39688,Abe Roeker,537445,689,Northwestern Dr,438969447
8,10010,Muoi Cary,385336,741,Northwestern Dr,828638512
9,40760,Renata Faver,976650,745,Northwestern Dr,547572040
10,25615,Olevia Morena,388477,812,Northwestern Dr,962831331
11,99826,Ivy Kazarian,994470,892,Northwestern Dr,208359813
12,44542,Ivory Mcgrevey,873842,897,Northwestern Dr,988557407
13,55130,Shiloh Huntoon,472118,951,Northwestern Dr,826647644
14,33415,Homer Simpson,108392,981,Northwestern Dr,871392019
15,29608,Willetta Lurvey,800568,1028,Northwestern Dr,843751378
16,18376,Josh Shi,653712,1091,Northwestern Dr,193899001
17,22239,Dusty Sigafus,710517,1125,Northwestern Dr,724386723
18,70485,Andera Kostelecky,354822,1252,Northwestern Dr,787423012
19,23960,Kristopher Lagerberg,658777,1392,Northwestern Dr,492912529
20,71924,Laurie Scronce,774116,1418,Northwestern Dr,254883636
21,81052,Calvin Czelusniak,471483,1516,Northwestern Dr,657531837
22,72076,Courtney Bordeaux,324614,1707,Northwestern Dr,347966356
23,51552,Bonita Knie,764124,1726,Northwestern Dr,597137908
24,88423,Teri Ehrich,510876,1879,Northwestern Dr,248637345
25,81885,Kurtis Masuda,934201,2108,Northwestern Dr,201272595
26,96178,Galina Khuu,450248,2183,Northwestern Dr,398518185
27,80921,Donovan Yackley,222395,2386,Northwestern Dr,515049359
28,34352,Vincenza Burkhardt,436470,2512,Northwestern Dr,197913046
29,53699,Christian Pagano,628433,2585,Northwestern Dr,644772304
30,54564,Sammie Sengun,217286,2590,Northwestern Dr,848854310
31,90397,Dionna Kranwinkle,797260,2678,Northwestern Dr,278964807
32,34155,Allyson Lazenson,814209,2840,Northwestern Dr,991150469
33,59307,Cyril Yongue,753524,2903,Northwestern Dr,866057839
34,98593,Jonah Toner,578982,2947,Northwestern Dr,745853548
35,44004,Alison Eska,327797,2951,Northwestern Dr,306417867
36,68690,Yer Modest,852404,3046,Northwestern Dr,419238039
37,51114,Christena Saffell,814284,3055,Northwestern Dr,247657547
38,23044,Val Portlock,924989,3143,Northwestern Dr,100593316
39,28360,Rashad Cascone,924517,3212,Northwestern Dr,838907424
40,53076,Boris Bijou,664914,3327,Northwestern Dr,401191868
41,36378,Freddie Ellzey,267882,3449,Northwestern Dr,474117596
42,87456,Leonora Wolfsberger,215868,3483,Northwestern Dr,565203106
43,93509,Emmitt Aceuedo,916706,3491,Northwestern Dr,979073160
44,19420,Cody Schiel,890431,3524,Northwestern Dr,947110049
45,96595,Coretta Cubie,303645,3631,Northwestern Dr,378403829
46,73368,Torie Thalmann,773862,3697,Northwestern Dr,341559436
47,53890,Sophie Tiberio,957671,3755,Northwestern Dr,442830147
48,17729,Lasonya Wildey,439686,3824,Northwestern Dr,917817122
49,14887,Morty Schapiro,118009,4919,Northwestern Dr,111564949

In [ ]:
query2="""
SELECT *
FROM person
where name like 'Annabel%' and address_street_name="Franklin Ave"
;
"""

In [ ]:
pd.read_sql_query(query2,conn)

,id,name,license_id,address_number,address_street_name,ssn
0,16371,Annabel Miller,490173,103,Franklin Ave,318771143

In [ ]:
query3="""
SELECT *
FROM interview
where person_id='14887'
;
"""
pd.read_sql_query(query3,conn)

   person_id                                         transcript
0      14887  I heard a gunshot and then saw a man run out. ...

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [ ]:
query3="""
SELECT *
FROM interview
where person_id='16371'
;
"""
pd.read_sql_query(query3,conn)

   person_id                                         transcript
0      16371  I saw the murder happen, and I recognized the ...

In [ ]:
query3="""
SELECT *
FROM get_fit_now_check_in
where membership_id like '48Z%' and check_in_date='20180109'
;
"""
pd.read_sql_query(query3,conn)

  membership_id  check_in_date  check_in_time  check_out_time
0         48Z7A       20180109           1600            1730
1         48Z55       20180109           1530            1700

In [ ]:
query3="""
SELECT *
FROM get_fit_now_member
where id='48Z7A'
;
"""
pd.read_sql_query(query3,conn)

      id  person_id          name  membership_start_date membership_status
0  48Z7A      28819  Joe Germuska               20160305              gold

In [ ]:
query3="""
SELECT *
FROM get_fit_now_member
where id='48Z55'
;
"""
pd.read_sql_query(query3,conn)

      id  person_id           name  membership_start_date membership_status
0  48Z55      67318  Jeremy Bowers               20160101              gold

In [ ]:
query3="""
SELECT *
FROM person
where id='28819'
;
"""
pd.read_sql_query(query3,conn)

,id,name,license_id,address_number,address_street_name,ssn
0,28819,Joe Germuska,173289,111,Fisk Rd,138909730

In [ ]:
query3="""
SELECT *
FROM person
where id='67318'
;
"""
pd.read_sql_query(query3,conn)

,id,name,license_id,address_number,address_street_name,ssn
0,67318,Jeremy Bowers,423327,530,"Washington Pl, Apt 3A",871539279

In [ ]:
query3="""
SELECT *
FROM drivers_license
where id='173289'
;
"""
pd.read_sql_query(query3,conn)

Empty DataFrame
Columns: [id, age, height, eye_color, hair_color, gender, plate_number, car_make, car_model]
Index: []

In [ ]:
query3="""
SELECT *
FROM drivers_license
where id='423327'
;
"""
pd.read_sql_query(query3,conn)

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,423327,30,70,brown,brown,male,0H42W2,Chevrolet,Spark LS

**Jeremy Bowers** is the murderer

In [ ]:
query3="""
SELECT *
FROM drivers_license
where hair_color='red' and gender='female' and car_make='Tesla'and car_model='Model S'
;
"""
pd.read_sql_query(query3,conn)

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,202298,68,66,green,red,female,500123,Tesla,Model S
1,291182,65,66,blue,red,female,08CM64,Tesla,Model S
2,918773,48,65,black,red,female,917UU3,Tesla,Model S

In [ ]:
query3="""
SELECT *
FROM person
where license_id IN(202298,291182,918773)
;
"""
pd.read_sql_query(query3,conn)

,id,name,license_id,address_number,address_street_name,ssn
0,78881,Red Korb,918773,107,Camerata Dr,961388910
1,90700,Regina George,291182,332,Maple Ave,337169072
2,99716,Miranda Priestly,202298,1883,Golden Ave,987756388

In [ ]:
query3="""
SELECT *
FROM facebook_event_checkin
where person_id IN(78881,90700,99716)
;
"""
pd.read_sql_query(query3,conn)

   person_id  event_id            event_name      date
0      99716      1143  SQL Symphony Concert  20171206
1      99716      1143  SQL Symphony Concert  20171212
2      99716      1143  SQL Symphony Concert  20171229

**Miranda Priestly**	is the one who had given a deal to murderer